### ISSUE TITLE
Peertalk Examples does not run on Xcode 6.4 and Yosemite 10.10.5

### ISSUE THREAD

**Issue by IntelBob** [rsms/peertalk#23]
Per step 2 of your getting started steps, running Peertalk example target caused 6 Semantic issue error, e.g, 
peertalk/peertalk/PTUSBHub.m:485:5: Objc_precise_lifetime only applies to retainable types; type here is 'dispatch_data_t' (aka 'struct dispatch_data_s *')
peertalk/peertalk/PTUSBHub.m:515:7: Objc_precise_lifetime only applies to retainable types; type here is 'dispatch_data_t' (aka 'struct dispatch_data_s *')
peertalk/peertalk/PTProtocol.m:216:7: Objc_precise_lifetime only applies to retainable types; type here is 'dispatch_data_t' (aka 'struct dispatch_data_s *')

Actually step 1 running unit tests for peertalk target also failed
peertalk/peertalk/PTProtocol.m:216:7: Objc_precise_lifetime only applies to retainable types; type here is 'dispatch_data_t' (aka 'struct dispatch_data_s *')

**Comment by angel77777** [comment]
The same happens here.
![schermata 2015-08-21 alle 18 49 27](https://cloud.githubusercontent.com/assets/13746391/9554835/285fd004-4dc9-11e5-9670-6e310941f8f9.png)

**Comment by javest** [comment]
I solved the same issue by commenting in PTPrivate.h the following rows:

//#define PT_PRECISE_LIFETIME __attribute__((objc_precise_lifetime))
//#define PT_PRECISE_LIFETIME_UNUSED __attribute__((objc_precise_lifetime, unused))

Then i converted the test for XC test.

Does this commented define can cause some side effects?

**Comment by javest** [comment]
...But after the build succeded, i launched the OS X example: it runs. When i launch de iOS example, the connection end with error. "Domain=NSPOSIXErrorDomain Code=89 "The operation couldn't be completed. Operation canceled". This happens a kind of loop where the iOS app try to connect on different port. 127.0.0.1:50312 then 17.0.0.1:50313 and so on. But the connection goes down. The same thing happens if i use my ipad air 2 with connected via usb to mac. Could you help me please?

**Comment by maydin** [comment]
@javest i applied what you said and it worked. i removed those two lines and it worked.

**Comment by jonathandann** [comment]
https://github.com/rsms/peertalk/releases/tag/0.1.0 works with Xcode 12.3.
