### ISSUE TITLE
Cross plattform support

### ISSUE THREAD

**Issue by mradke** [rsms/peertalk#35]
This is rather a RFC than an actual issue.

I would be happy to connect an iPad as a additional screen to my Linux system via a wired connection. One application that does it for Mac OS is the awesome Duett Display app you mention in the readme and which lead me here [1].

Would it be possible to use this library from a Linux system now that at least parts of libcentraldispatch are getting ported [2]?

Or would I be better off reimplementing the functionality utilizing usbmuxd [3] to achieve the same goals?

Thank you for your time! 👍 

- [1] https://github.com/deanm/deanm.github.com/blob/master/_posts/2014-12-18-DuetDisplay.markdown
- [2] https://github.com/apple/swift-corelibs-libdispatch
- [3] https://github.com/libimobiledevice/usbmuxd

**Comment by wasdee** [comment]
You could use it on linux. See the links below
http://makezine.com/2013/04/22/peertalk-beaglebone-and-raspberry-pi/

**Comment by rsms** [comment]
Duet Display actually uses PeerTalk (or at least it used to), so your idea is sound. PeerTalk is actually a usbmuxd "client", meaning you can use it to speak with usbmuxd running on any system as long as it talks the same protocol as Apple's version does. And this might be a tricky part, since Apple's usbmuxd implementation sends messages encoded in their favorite NeXT format "Property Lists" (aka "plist").

I encourage you to fork & hack on this :)

**Comment by mradke** [comment]
Hey thanks for the answers to the both of you!
This is some great news :-) I will eventually get into it when I have some time at my hands again.
